doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\CoreContext': '%kernel.project_dir%/src/CoreContext/Infrastructure/Migrations'
        'App\CrmContext': '%kernel.project_dir%/src/CrmContext/Infrastructure/Migrations'
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
